remote_theme: pmarsceill/just-the-docs

aux_links:
  "Orion Talk":
    - "https://github.com/orion-services/talk"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2023 Orion Services. Distributed by Apache 2.0 license."